# Ubuntu 18.10 (Cosmic Cuttlefish) as base image
FROM ubuntu:18.10

MAINTAINER Prashant Shahi "coolboi567@gmail.com"

# Setting work directory
WORKDIR /usr/src/app

# Copying requirements.txt to docker demon
COPY requirements.txt ./

# Installing dependencies
RUN apt-get update && \
	apt-get install -y python3-pip &&\
	pip3 install --no-cache-dir -r requirements.txt

# Copying the complete source code to the work directory
COPY . .

# Exposing port 5000
EXPOSE 5000

# Running the app
CMD [ "python3", "main.py" ]